services:

  backend:
    build:
      context: ./backend-app
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
